<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gudang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gudang_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'gudang/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'gudang/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'gudang/index.html';
            $config['first_url'] = base_url() . 'gudang/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Gudang_model->total_rows($q);
        $gudang = $this->Gudang_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'gudang_data' => $gudang,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'judul_page' => 'gudang/gudang_list',
            'konten' => 'gudang/gudang_list',
        );
        $this->load->view('v_index', $data);
    }

    public function read($id) 
    {
        $row = $this->Gudang_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_gudang' => $row->id_gudang,
		'nama_gudang' => $row->nama_gudang,
	    );
            $this->load->view('gudang/gudang_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gudang'));
        }
    }

    public function create() 
    {
        $data = array(
            'judul_page' => 'gudang/gudang_form',
            'konten' => 'gudang/gudang_form',
            'button' => 'Create',
            'action' => site_url('gudang/create_action'),
	    'id_gudang' => set_value('id_gudang'),
	    'nama_gudang' => set_value('nama_gudang'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_gudang' => $this->input->post('nama_gudang',TRUE),
	    );

            $this->Gudang_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('gudang'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Gudang_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => 'gudang/gudang_form',
                'konten' => 'gudang/gudang_form',
                'button' => 'Update',
                'action' => site_url('gudang/update_action'),
		'id_gudang' => set_value('id_gudang', $row->id_gudang),
		'nama_gudang' => set_value('nama_gudang', $row->nama_gudang),
	    );
            $this->load->view('v_index', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gudang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_gudang', TRUE));
        } else {
            $data = array(
		'nama_gudang' => $this->input->post('nama_gudang',TRUE),
	    );

            $this->Gudang_model->update($this->input->post('id_gudang', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('gudang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Gudang_model->get_by_id($id);

        if ($row) {
            $this->Gudang_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('gudang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gudang'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_gudang', 'nama gudang', 'trim|required');

	$this->form_validation->set_rules('id_gudang', 'id_gudang', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Gudang.php */
/* Location: ./application/controllers/Gudang.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2020-04-02 12:24:34 */
/* https://jualkoding.com */